# Bussiness Problem - Predict the Price of Banglore House

**Using Support Vector Regression - Supervised Machine Learning Algorithm **

**LOAD LIBRARIES **

In [1]:
import pandas as pd


**LOAD DATA **

In [2]:
df=pd.read_csv('/content/bangalore house price prediction OHE-data.csv')
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

SPLIT DATA

In [3]:
X=df.drop('price',axis=1)
y=df['price']


In [4]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train , y_test=train_test_split(X,y,test_size=0.25,random_state=51)


In [5]:
print("Shape of X_train",X_train.shape)
print("Shape of X_test",X_test.shape)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)


Shape of X_train (5340, 107)
Shape of X_test (1780, 107)
Shape of y_train (5340,)
Shape of y_test (1780,)


FEATURE SCALING

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

# SUPPORT VECTOR REGRESSION-MODEL TRAINING

In [8]:
from sklearn.svm import SVR
regressin_classifier=SVR(kernel="rbf")


In [9]:
regressin_classifier.fit(X_train,y_train)

SVR()

In [10]:
regressin_classifier.score(X_test,y_test)

0.22303432342840457

In [11]:
#kernel=linear
regress_linear=SVR(kernel="linear")
regress_linear.fit(X_train,y_train)
regress_linear.score(X_test,y_test)



0.8023607354213271

In [12]:
#kernel=ploy
regress_poly=SVR(kernel="poly")
regress_poly.fit(X_train,y_train)
regress_poly.score(X_test,y_test)


0.2741207968207199

PREDICT THE VALUE OF HOME AND TEST


In [13]:
X_test[0]

array([ 0.70963976,  0.01018102,  0.29243168,  0.65625116, -0.48209476,
       -1.74249281,  2.12119897, -0.25331599,  0.50847171, -0.18352593,
       -0.16468333, -0.14769566, -0.13313307, -0.13018891, -0.12641889,
       -0.12332528, -0.13240275, -0.12488108, -0.12175082, -0.11608205,
       -0.11100574, -0.10926391, -0.10478878, -0.1074952 , -0.09423191,
       -0.08465877, -0.09009885, -0.09009885, -0.08577355, -0.09321525,
       -0.08796197, -0.08238526, -0.08352953, -0.07389428, -0.07764429,
       -0.07764429, -0.07260223, -0.08004899, -0.07389428, -0.0751646 ,
       -0.0699481 , -0.07885558, -0.07260223, -0.07885558, -0.07641427,
       -0.0812253 , -0.06577042, -0.07641427, -0.0685833 , -0.07389428,
       -0.0699481 , -0.07128727, -0.07389428, -0.0685833 , -0.06283399,
       -0.06131393, -0.06283399, -0.06577042, -0.06431869, -0.05651272,
       -0.05815657, -0.06577042, -0.06719131, -0.06283399, -0.06577042,
       -0.05975581, -0.06577042, -0.06431869, -0.06131393, -0.06

In [15]:
regress_linear.predict([X_test[0]])

array([86.39967826])

In [16]:
y_pred=regress_linear.predict(X_test)
y_pred

array([ 86.39967826,  33.73728115, 122.50116323, ...,  37.22199639,
        73.87130203,  69.92087382])

In [17]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
4887     57.00
3311    150.00
2333     40.00
4594     71.55
3164     69.00
Name: price, Length: 1780, dtype: float64

In [18]:
from sklearn.metrics import mean_squared_error
import numpy as np
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print("Mean square error",mse)
print("Root Mean Square error",rmse)


Mean square error 3509.9798204351973
Root Mean Square error 59.245082668819
